// Image generation client for /api/imagegen. Generated bytes live on the backend
// under ~/.snowan/artifacts/imagegen/<id>.png; the UI references them by id via
// imageFileUrl. Library independence is achieved by copying an image to a new id.
import { api } from './base';

export type GenImage = { id: string; width: number | null; height: number | null };
export type GenerateRequest = {
  prompt: string;
  size?: string;
  n?: number;
  provider?: string | null;
  model?: string | null;
};
export type GenerateResult = { images: GenImage[]; revised_prompt: string | null };

async function j<T>(res: Response): Promise<T> {
  if (!res.ok) throw new Error(`${res.status} ${await res.text().catch(() => '')}`);
  return res.json();
}

export const generateImage = (req: GenerateRequest) =>
  fetch(api('/api/imagegen/generate'), {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(req),
  }).then(j<GenerateResult>);

export const imageFileUrl = (id: string) => api(`/api/imagegen/file/${id}`);

export const deleteImage = (id: string) =>
  fetch(api(`/api/imagegen/file/${id}`), { method: 'DELETE' }).then(j<{ ok: boolean }>);

export const copyToLibrary = (id: string) =>
  fetch(api(`/api/imagegen/file/${id}/copy`), { method: 'POST' }).then(j<{ id: string }>);

export const deleteImages = (ids: string[]) =>
  fetch(api('/api/imagegen/files/delete'), {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ ids }),
  }).then(j<{ ok: boolean }>);
